version: '2.2'

services:
  jenkins:
    image: windsekirun/jenkins-android-docker:1.1.4
    container_name: jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - "./jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
        TZ: "Asia/Seoul
    restart: always
